import type { Metadata } from 'next'
import { Inter, Roboto, Agbalumo } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })
// const inter = Roboto({ weight: '400', subsets: ['latin'] })
const inter = Agbalumo({ weight: '400', subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
